In [25]:
class animal():
    '''this is doc'''
    def __init__(self,name,kind):
        self.name = name
        self.kind = kind
       
    def getName(self):
        return self.name
    def getKind(self):
        return self.kind
    def changeName(self,newname):
        self.name=newname
    def __str__(self):
        return(self.name+'--'+self.kind)

In [6]:
A=animal('cat','mammal')

In [7]:
A.__class__

__main__.animal

In [13]:
A.__doc__

In [14]:
dir(A)

['__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 'changeName',
 'getKind',
 'getName',
 'kind',
 'name']

In [15]:
A.getName.__doc__

In [17]:
help(A)

Help on animal in module __main__ object:

class animal(builtins.object)
 |  Methods defined here:
 |  
 |  __init__(self, name, kind)
 |  
 |  changeName(self, newname)
 |  
 |  getKind(self)
 |  
 |  getName(self)
 |  
 |  ----------------------------------------------------------------------
 |  Data descriptors defined here:
 |  
 |  __dict__
 |      dictionary for instance variables (if defined)
 |  
 |  __weakref__
 |      list of weak references to the object (if defined)



In [27]:
A=animal('cat','mammal')

In [28]:
print (A)

cat--mammal


In [29]:
class Cat(animal):
    def __init__():
        pass

In [31]:
class cat_asia(Cat):
    def __init__():
        pass             #多重继承

In [34]:
from numpy import array
a=array([[0,1,2,3,4,5],
       [10,11,12,13,14,15],
       [20,21,22,23,24,25],
       [30,31,32,33,34,35]])

In [35]:
import numpy as np

In [36]:
a[2,2]

22

In [37]:
a[:,0]

array([ 0, 10, 20, 30])

In [38]:
a[0]

array([0, 1, 2, 3, 4, 5])

In [39]:
a=array([[0,1,2,3,4,5],
       [10,11,12,13,14,15],
       [20,21,22,23,24,25],
       [30,31,32,33,34,35],
        [40,41,42,43,44,45]])

In [40]:
a[::2,::2]

array([[ 0,  2,  4],
       [20, 22, 24],
       [40, 42, 44]])

In [41]:
a[(0,2,3),::2]

array([[ 0,  2,  4],
       [20, 22, 24],
       [30, 32, 34]])

In [42]:
a.max()

45

In [43]:
a.sum()

675

In [44]:
a.mean()

22.5

In [45]:
a.std() #标准差

14.244882121894399

In [48]:
a.any() #是否全为0

True

In [47]:
a.var()

202.91666666666666

In [49]:
a=range(0,10)

In [51]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [52]:
b=np.zeros((5,5))
b

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [53]:
b.any()

False

In [54]:
b=np.linespace(0,10,5)

AttributeError: module 'numpy' has no attribute 'linespace'